name: ci
on:
    push:
        branches:
            - master
    pull_request:

jobs:
    wasm:
        name: Run tests in wasm
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Install Rust
                uses: dtolnay/rust-toolchain@stable
                with:
                    targets: wasm32-unknown-unknown

            -   uses: actions/setup-node@v4

            -   name: Install wasm-pack
                run: cargo install wasm-pack

            -   name: Run tests default features
                run: wasm-pack test --node --features rust_crypto,getrandom/js

            -   name: Run tests no features
                run: wasm-pack test --node --no-default-features --features rust_crypto,getrandom/js
